### PR TITLE
Make bootkube report Helm installation errors faster and respect global asset timeout

### LINKED ISSUE #16: Inconsistent timeout when bootkube fails to startup
Currently its seems that the code has a timeout set as seen [here](https://github.com/kinvolk/bootkube/blob/kinvolk-master/pkg/bootkube/bootkube.go#L14)

However, this is not followed or there is a bug.

Output from different Lokomotive pipelines confirm this:

[This build is still ongoing at the time of writing](https://yard.lokomotive-k8s.net/builds/43351)
```
module.packet-ci1606199406-al.null_resource.bootkube-start: Still creating... [1h12m0s elapsed]
module.packet-ci1606199406-al.null_resource.bootkube-start: Still creating... [1h12m10s elapsed]
```

[Packet pipeline when the build stopped due to timeout](https://yard.lokomotive-k8s.net/builds/43352)
```
module.packet-ci1606199412-bd.null_resource.bootkube-start: Still creating... [51m10s elapsed]
module.packet-ci1606199412-bd.null_resource.bootkube-start: Still creating... [51m20s elapsed]
module.packet-ci1606199412-bd.null_resource.bootkube-start: Still creating... [51m30s elapsed]
```
[AWS pipeline](https://yard.lokomotive-k8s.net/builds/43350)
```
module.aws-ci1606199395-yy.null_resource.bootkube-start: Still creating... [55m40s elapsed]
module.aws-ci1606199395-yy.null_resource.bootkube-start: Still creating... [55m50s elapsed]
module.aws-ci1606199395-yy.null_resource.bootkube-start: Still creating... [56m0s elapsed]
```

### LINKED ISSUE #18: Exit immidiately if any of Helm chart installation fails
Right now we wait for all charts to converge, even if one fails to install. We should exit immidiately, as charts has most likely dependencies between each other, so we should report error early.

### PR DESCRIPTION
**Pull request by invidian**
Closes #16
Closes #18

### CODE REVIEW

File: pkg/helm/helm.go [hunk 1]
```diff
@@ -109,6 +110,7 @@ func installChart(kubeconfigPath, namespace, chartName, chartPath string) error
 	install.Namespace = namespace
 	install.CreateNamespace = true
 	install.Wait = true
+	install.Timeout = installTimeout
```
Comment (knrt10) [inline pkg/helm/helm.go:111]: just to confirm, what will be the value for `installTimeout`?

Comment (invidian) [reply pkg/helm/helm.go:111]: 20 minutes, the same as global bootkube assets timeout.

**Review by knrt10 — APPROVED** [review]
+1

**Review by iaguis — APPROVED** [review]
