### PR TITLE
pkg/helm: fix Helm logger formatting

### LINKED ISSUE #14: Fix logs formatting
Currently, it seems wrong:
```
kube-system/calico: creating [1] resource(s)
kube-system/kubelet: creating [1] resource(s)
kube-system/bootstrap-secrets: creating [1] resource(s)
kube-system/calico: creating [1] resource(s)
kube-system/kubelet: creating [1] resource(s)
kube-system/calico: creating [1] resource(s)
kube-system/bootstrap-secrets: beginning wait for [0 0] resources with timeout of %!v(MISSING)
kube-system/calico: creating [1] resource(s)
kube-system/kubelet: beginning wait for [1 0] resources with timeout of %!v(MISSING)
lokomotive-system/lokomotive: creating [1] resource(s)
kube-system/calico: creating [1] resource(s)
lokomotive-system/lokomotive: creating [5] resource(s)
kube-system/calico: creating [1] resource(s)
kube-system/kube-apiserver: creating [1] resource(s)
kube-system/calico: Clearing discovery cache
%!(EXTRA []interface {}=[])kube-system/calico: beginning wait for [15 60000000000] resources with timeout of %!v(MISSING)
kube-system/pod-checkpointer: creating [1] resource(s)
kube-system/kube-apiserver: creating [5] resource(s)
kube-system/pod-checkpointer: creating [9] resource(s)
lokomotive-system/lokomotive: beginning wait for [5 0] resources with timeout of %!v(MISSING)
kube-system/kube-apiserver: beginning wait for [5 0] resources with timeout of %!v(MISSING)
kube-system/pod-checkpointer: beginning wait for [9 0] resources with timeout of %!v(MISSING)
kube-system/kubernetes: creating [1] resource(s)
kube-system/kubernetes: creating [33] resource(s)
Release "bootstrap-secrets" created
Release "kubelet" created
Release "pod-checkpointer" created
kube-system/calico: creating [1] resource(s)
kube-system/calico: creating [11] resource(s)
lokomotive-system/lokomotive: Deployment is not ready: [lokomotive-system admission-webhook-server %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/kube-apiserver: Deployment is not ready: [kube-system kube-apiserver %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
lokomotive-system/lokomotive: Deployment is not ready: [lokomotive-system admission-webhook-server %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/kube-apiserver: Deployment is not ready: [kube-system kube-apiserver %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
lokomotive-system/lokomotive: Deployment is not ready: [lokomotive-system admission-webhook-server %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/kube-apiserver: Deployment is not ready: [kube-system kube-apiserver %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/kubernetes: beginning wait for [33 0] resources with timeout of %!v(MISSING)
lokomotive-system/lokomotive: Deployment is not ready: [lokomotive-system admission-webhook-server %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/kube-apiserver: Deployment is not ready: [kube-system kube-apiserver %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
Release "kubernetes" created
kube-system/calico: beginning wait for [11 0] resources with timeout of %!v(MISSING)
lokomotive-system/lokomotive: Deployment is not ready: [lokomotive-system admission-webhook-server %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/kube-apiserver: Deployment is not ready: [kube-system kube-apiserver %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/calico: Deployment is not ready: [kube-system calico-kube-controllers %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
lokomotive-system/lokomotive: Deployment is not ready: [lokomotive-system admission-webhook-server %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/kube-apiserver: Deployment is not ready: [kube-system kube-apiserver %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/calico: Deployment is not ready: [kube-system calico-kube-controllers %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
lokomotive-system/lokomotive: Deployment is not ready: [lokomotive-system admission-webhook-server %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/kube-apiserver: Deployment is not ready: [kube-system kube-apiserver %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/calico: Deployment is not ready: [kube-system calico-kube-controllers %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
lokomotive-system/lokomotive: Deployment is not ready: [lokomotive-system admission-webhook-server %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/kube-apiserver: Deployment is not ready: [kube-system kube-apiserver %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/calico: Deployment is not ready: [kube-system calico-kube-controllers %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
lokomotive-system/lokomotive: Deployment is not ready: [lokomotive-system admission-webhook-server %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
kube-system/kube-apiserver: Deployment is not ready: [kube-system kube-apiserver %!s(int32=0) %!s(int32=1)]/%!s(MISSING). %!d(MISSING) out of %!d(MISSING) expected pods are ready
```

### PR DESCRIPTION
**Pull request by invidian**
Regression introduced in d290a286063384fb247a5a8053cd9a45e7b20425, where
log helper function did not properly expand given arguments, which
resulted in passing them to util.UserOutput function as a slice instead
of as separate arguments, which caused log messages to be formatted
incorrectly.

This commit fixes it and adds unit test to verify expected behavior.

Closes #14

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

### CODE REVIEW

**Comment by invidian** [comment]
This seems to be looking good: https://yard.lokomotive-k8s.net/builds/42358.

File: pkg/helm/util_test.go [hunk 1]
```diff
@@ -110,3 +112,44 @@ func TestLoadValuesFile(t *testing.T) {
...
+		var buf bytes.Buffer
+		io.Copy(&buf, r)
+		outC <- buf.String()
+	}()
+
+	// Back to normal state.
+	w.Close()
+
+	// Restoring the real stdout.
+	os.Stdout = old
```
Comment (ipochi) [inline pkg/helm/util_test.go:141]: Perhaps I don't understand this, but what happens to the backup stdout while `printFunction()` is executing ? I mean would it miss any stdouts in the interim ?

**Review by ipochi — APPROVED** [review]
LGTM :tada: 

Just one question addressed as a comment.

File: pkg/helm/util_test.go (hunk 1 above)
Comment (invidian) [reply pkg/helm/util_test.go:141]: Nothing happens to it. We just keep a reference to a file descriptor, which is later on restored.

If something gets executed in parallel to `printFunction()`, then it will affect the output of this function, but this is expected. That's why tests using it shouldn't use `t.Parallel()` to ensure that only one is being executed at a time.
